#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-  .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-'   `-`-'   `-`-'
#
#                       Reusable workflow that builds the code
#
#   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-.   .-.-  .-.-.   .-.-.   .-.-
#  / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ \ / / \ / / \ \ / / \ \ / / \
# `-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-`-'   `-'   `-`-'   `-`-'
name: Test code

on:
  push

# We'll default the NPM_TOKEN to an empty value since we use it
# in .npmrc file and if undefined, the node setup would fail
env:
  NPM_TOKEN: ""

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
            path: node_modules/.cache/turbo
            key: ${{ runner.os }}-${{ runner.arch }}-turbo-${{ github.ref_name }}-${{ github.sha }}
            # The hierarchy of restoring the cache goes as follows:
            #
            # - First we try to match an existing cache from the same branch
            # - Then we try to match a cache from the target branch of this PR (if this is not a PR, this cache will never exist)
            # - Then we try to match a cache from the default branch
            # - Then we try to match any cache
            restore-keys: |
                ${{ runner.os }}-${{ runner.arch }}-turbo-${{ github.ref_name }}-
                ${{ runner.os }}-${{ runner.arch }}-turbo-${{ github.base_ref }}-
                ${{ runner.os }}-${{ runner.arch }}-turbo-${{ github.event.repository.default_branch }}-
                ${{ runner.os }}-${{ runner.arch }}-turbo-

      # We'll run the build in series to avoid race conditions
      # when compiling hardhat projects in monorepo setups
      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production